package Multi_Threading.ThreadTest;

//Getting and Setting name of a thread.
//Every thread in java has some name it may be default name generated by jvm are customised a name proved by programmer.
//We can get and set name of a thread by using the following two methods of thread class -
// 1. public final String getName()
// 2. public final void String setName()

class Mythread extends Thread {
}
class Demo extends Thread {
    public void run() {
        System.out.println("The run method executed by Thread: " + Thread.currentThread().getName());
    }
}

public class ThreadName {
    public static void main(String[] args) {
//        Mythread
        System.out.println(Thread.currentThread().getName());
        Mythread t = new Mythread();
        System.out.println(t.getName());
        Thread.currentThread().setName("xyz");
        System.out.println(Thread.currentThread().getName());

//        Demo
        System.out.println("-------------------------------------");
        Demo t1 = new Demo();
        t1.start();
        System.out.println("The run method executed by Thread: " + Thread.currentThread().getName());

//NOTE: We can get current executing thread object by using Thread.currentThread() method.
    }
}
